Document: mingw-w64-libunistring
Title: Debian mingw-w64-libunistring Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-libunistring is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-libunistring/mingw-w64-libunistring.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-libunistring/mingw-w64-libunistring.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-libunistring/mingw-w64-libunistring.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-libunistring/html/index.html
Files: /usr/share/doc/mingw-w64-libunistring/html/*.html
